---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: recreate-dep
  namespace: demo-ns
spec:
  replicas: 3
  selector:
    matchLabels:
      app: demo-pod
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 50%
      maxUnavailable: 50%
  minReadySeconds: 50
  template:
    metadata:
      labels:
        app: demo-pod
    spec:
      containers:
        - name: onlinebookstore-dep
          image: mahendragowda007/bookstore:REPLACE_TAG
          ports:
            - containerPort: 8080

---
apiVersion: v1
kind: Service
metadata:
  name: tomcat-service
  namespace: demo-ns
spec:
  type: NodePort
  selector:
    app: demo-pod
  ports:
    - port: 80
      targetPort: 8080
